### ISSUE TITLE
Better process.nextTick 

### ISSUE THREAD

**Issue by calvinmetcalf** [defunctzombie/node-process#28]
process.nextTick is somewhat slow here and fixing it is tricky because on one hand you don't want it to be big because it gets pulled into a huge number of libraries but on the other hand libraries that a user has no control over (like streams) use it meaning that stand alone async modules (like immediate and asap) can't solve the problem.

While perf tests tend to emphasize the latency of the async function (I. E. the mutation observer or postMessage or setTimeout) in an actual app this will be a bottleneck when it is called recursively or many times at once. At these points the async function only needs to be called once and the queue ends up being the bottleneck. 

It likely makes sense to get rid of most/all of the non setTimeout async functions and instead focus on making an efficient queue and point users needing low latency to things like asap and immediate. 

When it comes to a queue for microtasks there are 3 approaches I've seen, the first is to use an array this is what's done here (and I used to do in immediate) the problem is that array.shift has some serious performance impacts. 

Another used in asap and a lot of promise implementations that base their async on it quick is a circular buffer. This is fast but requires a circular buffer implementation which while not huge isn't nothing. 

A third solution (which I use in immediate) is to grow the array, and drain it with a while loop, this avoids the overhead of shifting the element's and the size of a circular buffer, the trick is to swap out the in use buffer with a new one before draining it and then repeating for the new one until the new one has nothing in it after the drain. The swapping avoids a massive slowdown in cases when the queue gets long enough that the index is no longer a small int (which can cause an order of magnitude slowdown and memory usage). The swapping queue thing would also allow you to gage depth of recursive NextTick usage and give a warning like in node. 

Thoughts?

**Comment by nathanbowser** [comment]
This commit has caused an insane amount of bugs since we've upgraded. Are we sure this is better?

**Comment by calvinmetcalf** [comment]
@nathanbowser can you be more specific ?

**Comment by nathanbowser** [comment]
@calvinmetcalf Yea, totally. I put it on my todo list to build two examples where things broke badly when I upgraded. Will have it shortly.

**Comment by slorber** [comment]
@calvinmetcalf @nathanbowser this breaks Q lib too.

See https://github.com/substack/node-browserify/issues/1179

**Comment by slorber** [comment]
I've made a PR here: https://github.com/defunctzombie/node-process/pull/37
