### ISSUE TITLE
process.nextTick shim should use Promise.resolve().then(fn) if available

### ISSUE THREAD

**Issue by domenic** [defunctzombie/node-process#32]
This is currently the fastest cross-environment way of creating a microtask. But more interestingly, it works in environments like the V8 shell where there is no setTimeout available to fall back to. (Why do I need browserify bundles to run inside the V8 shell you ask? MAD SCIENCE!)

(Originally https://github.com/substack/node-browserify/issues/1109)

**Comment by defunctzombie** [comment]
PR please and I will review :)

**Comment by domenic** [comment]
I realized I'm not sure how to do this in v8 shell since I'm not sure how to signal the error. Normally with promises you would signal any errors via a pattern like

```js
Promise.resolve().then(fn).catch(e => setTimeout(() => { throw e; }, 0));
```

but of course the original problem I'm trying to solve is the lack of setTimeout.

The only alternative I can think of is `console.error`ing the error. But in V8 shell `console` doesn't even exist! So at this point I should probably just insert my own v8-shell specific shim that uses `%EnqueueMicrotask()`.
