### ISSUE TITLE
missing process.versions 

### ISSUE THREAD

**Issue by sinkingshriek** [defunctzombie/node-process#33]
Hi,
I'm using `node-bindings` which has [this](https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L16) line that uses `process.versions`. I'm also using `browserify` which uses this module.  
From [this](https://github.com/defunctzombie/node-process/issues/14) issue it's quite clear to me that shimming wouldn't make sense but would it be okay to add `process.versions` in this module so that it doesn't throw an error?

**Comment by defunctzombie** [comment]
added in master

**Comment by sinkingshriek** [comment]
:smile: Thanks.
