### ISSUE TITLE
support process.chdir

### ISSUE THREAD

**Issue by wjordan** [defunctzombie/node-process#46]
BrowserFS provides a [basic implementation](https://github.com/jvilk/BrowserFS/blob/master/src/core/node_process.ts#L66-L93) of `chdir` and `cwd` in its own internal implementation of `process`. Would it be possible to include a similar implementation into this module, as a slight step up from the current [stubs](https://github.com/defunctzombie/node-process/blob/master/browser.js#L85-L89)?

**Comment by defunctzombie** [comment]
Please see this part of the readme about additional features: https://github.com/defunctzombie/node-process#browser-implementation

Happy to accept a PR to add it to the list on the readme but will not expand the size of this module due to those concerns.

**Comment by wjordan** [comment]
Thanks, I'll look to fill out this implementation elsewhere then. Perhaps removing the [`todo` comment](https://github.com/defunctzombie/node-process/blob/master/browser.js#L85) in the current source code would help to avoid future confusion.
