### ISSUE TITLE
process.versions.node is undefined

### ISSUE THREAD

**Issue by AshokKumarPathak** [defunctzombie/node-process#52]
I am doing browserify of “pdf2png-mp” npm module with following steps:
1. $ sudo npm install pdf2png-mp
2. $ browserify -r pdf2png-mp -o bundle.js
3. Created a html file that includes the following:

     <body>
      <script src="bundle.js"></script>
      <script> 
        var md = require('pdf2png-mp');
     </script>
    </body>
Actual Results:
“TypeError: Cannot read property 'split' of undefined” at bundle.js:667

var version = process.versions.node.split('.').map(function (value) {
return parseInt(value, 10);
});

Configuration:
Processor  2.5 GHz Intel Core i5
Memory  4 GB 1333 MHz DDR3
Software  Mac OS X 10.9.4 (13E28)

Version & Build:
browserify v12.0.0
npm v3.3.8

**Comment by calvinmetcalf** [comment]
so first off `pdf2png-mp` is not going to browserify even if this is fixed because it relies on some stuff that is impossible to browserify

more generally I wonder if it would be useful to fill up process.versions up with empty strings like process.version, e.g.

```js
process.versions = {
{
  http_parser: '',
  node: '',
  v8: '',
  uv: '',
  zlib: '',
  ares: '',
  icu: '',
  modules: '',
  openssl: ''
}
```

**Comment by AshokKumarPathak** [comment]
Thank you calvin for your input.

**Comment by defunctzombie** [comment]
@calvinmetcalf I think maybe not cause then someone else will have some script that checks for versions being an object and trying to query into the versions maybe. Can't please everyone :)
