### ISSUE TITLE
Extend even emitter instead of noop'ing those methods

### ISSUE THREAD

**Issue by wesleytodd** [defunctzombie/node-process#53]
Is there a reason to noop the event emitter methods instead of just extending from the [event emitter](https://www.npmjs.com/package/events)?

I was thinking of patching `process.on('uncaughtException', function(){})` with `window.onerror` to handle this in the browser, but I would have to also patch these methods.  I could submit a PR with all of this if that is something you are interested in having.  Let me know!

**Comment by calvinmetcalf** [comment]
the reason is because lots of people use this just for process.nextTick and
process.browser so we want to keep it as small as possible

**Comment by wesleytodd** [comment]
So the recommended method is to patch it with your own module?

**Comment by calvinmetcalf** [comment]
yeah that would probably be best, or create a module that works isomorphicly, returning process if it's in node and and event emitter you created otherwise that

**Comment by wesleytodd** [comment]
yeah, that is was I meant, just wasn't clear in my comment :)

**Comment by calvinmetcalf** [comment]
:+1: then
